### ISSUE TITLE
ImportError on Python3.5

### ISSUE THREAD

**Issue by guyskk** [axiaoxin/json2xls#2]
ImportError on Python3.5
```
Python 3.5.2 (default, Jun 28 2016, 08:46:01) 
[GCC 6.1.1 20160602] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from json2xls import Json2Xls
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/json2xls/__init__.py", line 132, in <module>
    from json2xls import Json2Xls
ImportError: cannot import name 'Json2Xls'
>>> import json2xls
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/json2xls/__init__.py", line 132, in <module>
    from json2xls import Json2Xls
ImportError: cannot import name 'Json2Xls'
>>> 
```

Python2.7 works well.

**Comment by guyskk** [comment]
Python2.7 didn't work too
```
Python 2.7.12 (default, Jun 28 2016, 08:31:05) 
[GCC 6.1.1 20160602] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from json2xls import Json2Xls
>>> 
>>> # 从json字符串生成excel
... json_data = u'''[
...     {"姓名": "John", "年龄": 30, "性别": "男"},
...     {"姓名": "Alice", "年龄": 18, "性别": "女"}
... ]'''
>>> obj = Json2Xls('tests/json_strlist_test.xls', json_data)
>>> obj.make()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/guyskk/.virtualenvs/py27/lib/python2.7/site-packages/json2xls/json2xls.py", line 210, in make
    self.book.save(self.xls_filename)
  File "/home/guyskk/.virtualenvs/py27/lib/python2.7/site-packages/xlwt/Workbook.py", line 696, in save
    doc.save(filename_or_stream, self.get_biff_data())
  File "/home/guyskk/.virtualenvs/py27/lib/python2.7/site-packages/xlwt/CompoundDoc.py", line 262, in save
    f = open(file_name_or_filelike_obj, 'w+b')
IOError: [Errno 2] No such file or directory: 'tests/json_strlist_test.xls'
>>> 
```

**Comment by axiaoxin** [comment]
没有在python 3.5下测试过，可以帮忙修复下哟：）

第二个报错信息看来应该是你需要建一个tests文件夹：）

**Comment by guyskk** [comment]
obj.make能返回二进制流这样的对象吗，或者是指定生成到某个目录里？

**Comment by axiaoxin** [comment]
'tests/json_strlist_test.xls'就是指定生成路径改成'/tmp/json_strlist_test.xls'之类的即可

**Comment by guyskk** [comment]
@axiaoxin 多谢，这个参数我明白了，但是不知道能不能返回二进制流这样的对象？

**Comment by axiaoxin** [comment]
不支持哦，可以帮助改进~~

**Comment by guyskk** [comment]
OK, 多谢，有空我再看看

**Comment by guyskk** [comment]
改不动。。还是继续用tablib比较好
